### ISSUE TITLE
Custom domain unexpectedly gets destroyed when deploying

### ISSUE THREAD

**Issue by HannesBenson** [boltops-tools/jets#551]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | Ubuntu Linux |
| Jets             | 3.0.2/3.0.5 |
| Ruby             | 2.7.0 |

---

## Expected Behaviour

When I have the following set in my stage config:
```
  config.domain.hosted_zone_name = 'my.cool-services.bar'
  config.domain.name = 'staging.my.cool-services.bar'
  config.domain.cert_arn = "arn:aws:acm:us-east-1:xxxxxxxxxxxxx:certificate/yyyyyyyyy-zzzz-aaaa-bbbb-dddddddddd"
  config.domain.route53 = true
```
and I deploy my jets app to lambda using `jets deploy staging`, I expect the DNS record to always be present and pointing at the latest stack.

## Current Behavior

When I use the described configuration and I deploy my jets app to lambda using `jets deploy staging`, the DNS record is removed if it exists and it is created when it was missing. This requires every deploy to be done twice to ensure the service is working as expected.

## Step-by-step reproduction instructions

1. Create a new jets app
2. Set the appropriate config for the staging/production environment
3. Deploy it, if there is no custom dns in AWS, the deploy will go out and work as expected. If the DNS record existed, this will be removed.

## Code Sample

Looking at the code from 2.3.x [here](https://github.com/boltops-tools/jets/blob/2.3.x/lib/jets/cfn/builders/api_gateway_builder.rb#L40) we can see that it added the custom domain if it was configured for jets. However, in 3.0.x [here](https://github.com/boltops-tools/jets/blob/master/lib/jets/cfn/builders/api_gateway_builder.rb#L52) we see that it checks if the domain already exists. This then leads to CloudFormation templates differing between the 2 deploys.
When the domain does exist:
```yml
---
Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: jets-stag
      EndpointConfiguration:
        Types:
          - EDGE
      BinaryMediaTypes:
        - multipart/form-data
Outputs:
  RestApi:
    Value: !Ref RestApi
  Region:
    Value: !Ref AWS::Region
  RootResourceId:
    Value: !GetAtt RestApi.RootResourceId
  RestApiUrl:
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/stag/"
  DomainName:
    Value: staging.my.cool-service.bar
```
When the domain doesn't exist:
```yml
---
Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: jets-stag
      EndpointConfiguration:
        Types:
          - EDGE
      BinaryMediaTypes:
        - multipart/form-data
  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: staging.my.cool-service.bar
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: certificate-arn-here
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: DNS record managed by Jets
      Name: staging.my.cool-service.bar
      HostedZoneName: my.cool-service.bar.
      Type: CNAME
      TTL: "60"
      ResourceRecords:
        - !GetAtt DomainName.RegionalDomainName
Outputs:
  RestApi:
    Value: !Ref RestApi
  Region:
    Value: !Ref AWS::Region
  RootResourceId:
    Value: !GetAtt RestApi.RootResourceId
  RestApiUrl:
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/stag/"
  DomainName:
    Value: !Ref DomainName
  DnsRecord:
    Value: !Ref DnsRecord
```

## Solution Suggestion

Stop checking if the record exists in AWS already as it breaks the documented feature.
